### ISSUE TITLE
Handle participating notifications separately

### ISSUE THREAD

**Issue by rvraghav93** [sindresorhus/notifier-for-github-firefox#10]
Many-a-times people watch repositories and will get a tonne of notifications as a result of that...

It would be super useful (at least for me ;)) if you could add an option to show an additional icon or an option or at least 2 number counts one for all the unread notifs and one for the participating notifs...

Thanks for the plugin btw! :)

**Comment by sindresorhus** [comment]
Maybe do what the Chrome extensions does and introduce an option to only show participating notifications: https://github.com/sindresorhus/notifier-for-github-chrome/blob/master/screenshot-webstore2.png

**Comment by sindresorhus** [comment]
This extension is now deprecated: https://github.com/sindresorhus/notifier-for-github-firefox/commit/ad714725ba2a22129c3786c660bae3cae154ce3f
