### ISSUE TITLE
[Feature Request] custom url

### ISSUE THREAD

**Issue by deguss** [sindresorhus/notifier-for-github-firefox#11]
Hi @seleznev! 
I just wanted to aks if you have time to update the firefox plugin with all the nice features the chrom plugin already has. At least the custom url would be nice for me. 
Thank you. Daniel

**Comment by sindresorhus** [comment]
Do separate issues for each feature you want and be specific about what that feature does.

**Comment by deguss** [comment]
Thank you, I am not yet familiar with the "usual way" here on github.
