### ISSUE TITLE
About the icon change

### ISSUE THREAD

**Issue by GizMecano** [sindresorhus/notifier-for-github-firefox#12]
Greetings,

I must admit that I'm not really convinced by the future change of icon (243c985a64d3fb0869b422e69f4969e75c1e8693) for this extension.

I understand that you have wanted to accord the new notification icon with your work, but if this bell is actually present on the notification page, visitors can also see the main logo which help them to know where they are. In the case of an icon placed in the browser, a bell doesn't clearly refer to a particular site such as GitHub. This icon alludes only to the notion of notification, not clearly to the notification from a definite site.

Currently, I suppose that two other possibilities could exist:

1. keep the previous icon and let users choose if they want to use the logo or the bell
2. use an dedicated icon which does not refer to GitHub nor to a bell but clearly to your own work

My two cents.

Regards

**Comment by sindresorhus** [comment]
I only changed the extension icon. Not toolbar icon. GitHub asked me to change it because of trademark stuff.

**Comment by GizMecano** [comment]
Oh damn! I have read the file names too fast. I suppose that I must apologize... Sorry.
