### ISSUE TITLE
Maintainer needed

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/notifier-for-github-firefox#15]
I haven't used this extension for years and it could use an active maintainer that actually cares and can review PRs, triage issues, etc.

**Comment by sean3z** [comment]
@sindresorhus I'd like to volunteer to help maintain this extension :smiley:

**Comment by sindresorhus** [comment]
@sean3z Thank you! I really appreciate it. Added you.

**Comment by sindresorhus** [comment]
The guidelines are simple. Be kind to everyone. Larger changes should come in a pull request. Smaller ones can be committed directly. Follow the existing [code style](https://github.com/sindresorhus/xo) (Tip: `$ xo --fix` can fix many issues) and ensure `npm test` passes before pushing a commit. You can use branches in this repo, but clean them up afterwards. I like a clean commit history, so when merging a pull request, either ask the contributor to [squash](http://stackoverflow.com/questions/11396069/squash-to-only-one-proper-commit-for-github-pull-request) their commits or do it for them manually.

**Comment by sindresorhus** [comment]
The next would be to start resolving the open issues. Feel free to open new issues for features you'd like to see. The [Chrome extension](https://github.com/sindresorhus/notifier-for-github-chrome) is more feature-rich, so might want to take some inspiration from it.

**Comment by oddRaven** [comment]
When do you decide to tag a commit with a new version? I understand the need for a clean commit history but the logs so far are rather confusing with some having only the version in the message.

**Comment by SamVerschueren** [comment]
@oddRaven Not sure if I fully understand the question but I'll give it a go :). When you release a new version from a module (in this case probably `notifier-for-github-firefox`), you first change the version as you can see in [this](https://github.com/sindresorhus/notifier-for-github-firefox/commit/5b4a5b1a750ebf0b2b215eeac0ec6d3de5ae884a) commit. The commit message is the same as the version and you add a tag with the same version number to that commit.

**Comment by oddRaven** [comment]
@SamVerschueren I think it would be more useful if the message contained information about what it changed, considering the tag covers the version.

**Comment by sindresorhus** [comment]
@oddRaven The tag commits are there to make it easy to see when in the history a version bump happened. This is common convention in the Node.js world and I guess other ecosystems too.

**Comment by oddRaven** [comment]
@sindresorhus I'd like to become a collaborator. How long should I wait before accepting my own pull requests, in case noone comments on them?

**Comment by sindresorhus** [comment]
Thank all for offering to help out. Unfortunately, this extension is now deprecated: https://github.com/sindresorhus/notifier-for-github-firefox/commit/ad714725ba2a22129c3786c660bae3cae154ce3f
