### ISSUE TITLE
 Your deprecation notice and links are cyclical 

### ISSUE THREAD

**Issue by xenithorb** [sindresorhus/notifier-for-github-firefox#19]
If you have deprecated this project in favor of notifier-for-github-chrome, then please include instructions on how to install this on Firefox, preferably an AMO link?

As it currently stands, the bold heading link takes you to notifier-for-github-chrome, but then offers no information on how to use that with Firefox. And no, I don't really want to disable signing. 

Can you submit these to AMO yet?

Is it premature to deprecate the -firefox variant?

**Comment by sindresorhus** [comment]
Firefox 48 is not out yet. It's just deprecated here so people don't waste time contributing to a project that is going away. You can continue using this plugin until Firefox 48 is out. When Firefox 48 is out I'm sure they'll post instructions on how to use Chrome extensions, which I can then link to.

I'll keep this open for discovery until such time.

**Comment by xenithorb** [comment]
I'm currently using it on FF 48 (Dev Edition) with : https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/

It works, except the desktop notification option is not saved.

**Comment by X-dark** [comment]
What about now?

**Comment by xenithorb** [comment]
No it's still not saved. Also clicking the icon when it has a notification does nothing. (as with the Firefox version I would have expected it to take me to the notifications page)

**Comment by X-dark** [comment]
My question was for @sindresorhus now that FF48 is released.
